general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # TURN ON SCREEN ON WAKE
}

# 1. Dim the Screen (Saves LOQ Battery)
listener {
    timeout = 150                                # 2.5 mins
    on-timeout = brightnessctl set 10%           # Dim backlights
    on-resume = brightnessctl set 100%           # Restore backlights
}

# 2. Lock the Screen
listener {
    timeout = 300                                # 5 mins
    on-timeout = loginctl lock-session
}

# 3. The "Anti-Black Screen" Suspend
listener {
    timeout = 330                                # 5.5 mins
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on         # FORCE WAKE NVIDIA SIGNAL
}